villager_dialoge_1 = 'hello'
villager_dialoge_2 = 'placeholder 1'
villager_dialoge_3 = 'placeholder 2'
villager_dialoge_4 = 'placeholder 3'
villager_dialoge_5 = 'placeholder 4'
villager_dialoge_6 = 'placeholder 5'